name: My GitHub Action

on:
  push:
    branches:
      - main

jobs:
  run-hjk-test-v1:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run hjk-test-v1 action
      uses: hyeonjeong-ko/test-pack-hjk@2
      with:
        input-param: "Hello, GitHub Action!"
    
    - name: Run Python script
      run: |
        python my_script.py
        # Add any additional commands or scripts you want to run here
