name: My GitHub Action

on:
  push:
    branches:
      - main

jobs:
  run-hjk-test-v1:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run hjk-test-v1 action
      uses: your-username/hjk-test-v1@v1.0.0
      with:
        input-param: "Hello, GitHub Action!"
