name: My GitHub Action

on:
  push:
    branches:
      - main

jobs:
  run-hjk-test-v1:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run hjk-test-v1 action
      uses: hyeonjeong-ko/packiging-test@1.2
      with:
        test-variable: "환경변수 테스트를 해보자~!!!하이!"
    
    - name: Run Python script
      run: |
        python hi.py
        # Add any additional commands or scripts you want to run here
