name: My GitHub Action

on:
  push:
    branches:
      - main

jobs:
  run-hjk-test-v1:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Run hjk-test-v1 action
      uses: hyeonjeong-ko/packiging-test@1.5
      with:
        test-variable: "파이썬 파일을 합쳐보자~!"
        send-to-function: "send_to_friends"
        rest-api-key: "152831f2d43d3d3c3b003a24ec2fa088"
        redirect_uri: "https://localhost:3000"
        code-key: "Oll_f6rGT-UfEDx5DAgnii_0bBJ_NfA3mfQqLSzXepE_nCJ1fNq0E5X-K5BlJtFXiUOxbwo9dJkAAAGKFdSwTA"
